============================= test session starts ==============================
platform darwin -- Python 3.11.11, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/salehgazwani/Documents/morvo13
configfile: pyproject.toml
testpaths: tests
plugins: asyncio-0.23.8, anyio-4.9.0, cov-4.1.0, mock-3.14.1
asyncio: mode=Mode.STRICT
collected 5 items

tests/api/v1/endpoints/test_auth.py FF                                   [ 40%]
tests/api/v1/endpoints/test_health.py .                                  [ 60%]
tests/api/v1/endpoints/test_seranking.py EEE                             [100%]

==================================== ERRORS ====================================
______________ ERROR at setup of test_analyze_domain_queues_task _______________
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:843: in _start_transaction
    await self._transaction.start()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/transaction.py:146: in start
    await self._connection.execute(query)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/connection.py:349: in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncpg/protocol/protocol.pyx:360: in query
    ???
asyncpg/protocol/protocol.pyx:745: in asyncpg.protocol.protocol.BaseProtocol._check_state
    ???
E   asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:347: in _asyncgen_fixture_wrapper
    result = event_loop.run_until_complete(setup())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:654: in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:329: in setup
    res = await gen_obj.__anext__()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
tests/conftest.py:76: in authorized_client
    response = await ac.post("/v1/auth/register", json=user_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1877: in post
    return await self.request(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1559: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1646: in send
    response = await self._send_handling_auth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1674: in _send_handling_auth
    response = await self._send_handling_redirects(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1711: in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1748: in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_transports/asgi.py:162: in handle_async_request
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:186: in __call__
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:164: in __call__
    await self.app(scope, receive, _send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:756: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:776: in app
    await route.handle(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:297: in handle
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:72: in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:278: in app
    raw_response = await run_endpoint_function(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:191: in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/api/v1/endpoints/auth.py:22: in register_user
    result = await db.execute(select(User).where(User.email == user_in.email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py:463: in execute
    result = await greenlet_spawn(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2365: in execute
    return self._execute_internal(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2251: in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/context.py:306: in orm_execute_statement
    result = conn.execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1415: in execute
    return meth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:523: in _execute_on_connection
    return connection._execute_clauseelement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1637: in _execute_clauseelement
    ret = self._execute_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1842: in _execute_context
    return self._exec_single_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1982: in _exec_single_context
    self._handle_dbapi_exception(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2351: in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
E   [SQL: SELECT users.id, users.email, users.hashed_password 
E   FROM users 
E   WHERE users.email = $1::VARCHAR]
E   [parameters: ('auth_test@example.com',)]
E   (Background on this error at: https://sqlalche.me/e/20/rvf5)
__________________ ERROR at setup of test_get_domain_history ___________________
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:843: in _start_transaction
    await self._transaction.start()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/transaction.py:146: in start
    await self._connection.execute(query)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/connection.py:349: in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncpg/protocol/protocol.pyx:360: in query
    ???
asyncpg/protocol/protocol.pyx:745: in asyncpg.protocol.protocol.BaseProtocol._check_state
    ???
E   asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:347: in _asyncgen_fixture_wrapper
    result = event_loop.run_until_complete(setup())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:654: in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:329: in setup
    res = await gen_obj.__anext__()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
tests/conftest.py:76: in authorized_client
    response = await ac.post("/v1/auth/register", json=user_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1877: in post
    return await self.request(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1559: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1646: in send
    response = await self._send_handling_auth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1674: in _send_handling_auth
    response = await self._send_handling_redirects(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1711: in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1748: in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_transports/asgi.py:162: in handle_async_request
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:186: in __call__
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:164: in __call__
    await self.app(scope, receive, _send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:756: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:776: in app
    await route.handle(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:297: in handle
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:72: in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:278: in app
    raw_response = await run_endpoint_function(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:191: in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/api/v1/endpoints/auth.py:22: in register_user
    result = await db.execute(select(User).where(User.email == user_in.email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py:463: in execute
    result = await greenlet_spawn(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2365: in execute
    return self._execute_internal(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2251: in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/context.py:306: in orm_execute_statement
    result = conn.execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1415: in execute
    return meth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:523: in _execute_on_connection
    return connection._execute_clauseelement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1637: in _execute_clauseelement
    ret = self._execute_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1842: in _execute_context
    return self._exec_single_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1982: in _exec_single_context
    self._handle_dbapi_exception(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2351: in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
E   [SQL: SELECT users.id, users.email, users.hashed_password 
E   FROM users 
E   WHERE users.email = $1::VARCHAR]
E   [parameters: ('auth_test@example.com',)]
E   (Background on this error at: https://sqlalche.me/e/20/rvf5)
_________________ ERROR at teardown of test_get_domain_history _________________
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:843: in _start_transaction
    await self._transaction.start()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/transaction.py:146: in start
    await self._connection.execute(query)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/connection.py:349: in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncpg/protocol/protocol.pyx:360: in query
    ???
asyncpg/protocol/protocol.pyx:745: in asyncpg.protocol.protocol.BaseProtocol._check_state
    ???
E   asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:345: in finalizer
    event_loop.run_until_complete(async_finalizer())
/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:654: in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:337: in async_finalizer
    await gen_obj.__anext__()
tests/conftest.py:42: in test_db
    await conn.run_sync(UserBase.metadata.drop_all)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py:887: in run_sync
    return await greenlet_spawn(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/schema.py:5952: in drop_all
    bind._run_ddl_visitor(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2455: in _run_ddl_visitor
    ).traverse_single(element)
      ^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py:664: in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py:1082: in visit_metadata
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py:1082: in <listcomp>
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
                                            ^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py:1158: in _can_drop_table
    return not self.checkfirst or self.dialect.has_table(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py:89: in cache
    return fn(self, con, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py:3477: in has_table
    return bool(connection.scalar(query, {"table_name": table_name}))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1304: in scalar
    return meth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:541: in _execute_on_scalar
    return self._execute_on_connection(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:523: in _execute_on_connection
    return connection._execute_clauseelement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1637: in _execute_clauseelement
    ret = self._execute_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1842: in _execute_context
    return self._exec_single_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1982: in _exec_single_context
    self._handle_dbapi_exception(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2351: in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
E   [SQL: SELECT pg_catalog.pg_class.relname 
E   FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
E   WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR]
E   [parameters: ('users', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')]
E   (Background on this error at: https://sqlalche.me/e/20/rvf5)
=================================== FAILURES ===================================
______________________________ test_register_user ______________________________
tests/api/v1/endpoints/test_auth.py:8: in test_register_user
    response = await client.post(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1877: in post
    return await self.request(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1559: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1646: in send
    response = await self._send_handling_auth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1674: in _send_handling_auth
    response = await self._send_handling_redirects(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1711: in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1748: in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_transports/asgi.py:162: in handle_async_request
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:186: in __call__
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:164: in __call__
    await self.app(scope, receive, _send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:756: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:776: in app
    await route.handle(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:297: in handle
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:72: in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:278: in app
    raw_response = await run_endpoint_function(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:191: in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/api/v1/endpoints/auth.py:22: in register_user
    result = await db.execute(select(User).where(User.email == user_in.email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py:463: in execute
    result = await greenlet_spawn(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2365: in execute
    return self._execute_internal(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2251: in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/context.py:306: in orm_execute_statement
    result = conn.execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1415: in execute
    return meth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:523: in _execute_on_connection
    return connection._execute_clauseelement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1637: in _execute_clauseelement
    ret = self._execute_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1842: in _execute_context
    return self._exec_single_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1982: in _exec_single_context
    self._handle_dbapi_exception(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2354: in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:794: in _handle_exception
    raise error
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:843: in _start_transaction
    await self._transaction.start()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/transaction.py:146: in start
    await self._connection.execute(query)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/connection.py:349: in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncpg/protocol/protocol.pyx:375: in query
    ???
E   RuntimeError: Task <Task pending name='Task-6' coro=<test_register_user() running at /Users/salehgazwani/Documents/morvo13/tests/api/v1/endpoints/test_auth.py:8> cb=[_run_until_complete_cb() at /opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop
___________________________ test_login_access_token ____________________________
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:843: in _start_transaction
    await self._transaction.start()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/transaction.py:146: in start
    await self._connection.execute(query)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/asyncpg/connection.py:349: in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncpg/protocol/protocol.pyx:360: in query
    ???
asyncpg/protocol/protocol.pyx:745: in asyncpg.protocol.protocol.BaseProtocol._check_state
    ???
E   asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:
tests/api/v1/endpoints/test_auth.py:19: in test_login_access_token
    await client.post(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1877: in post
    return await self.request(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1559: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1646: in send
    response = await self._send_handling_auth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1674: in _send_handling_auth
    response = await self._send_handling_redirects(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1711: in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_client.py:1748: in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/httpx/_transports/asgi.py:162: in handle_async_request
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:186: in __call__
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py:164: in __call__
    await self.app(scope, receive, _send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:756: in __call__
    await self.middleware_stack(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:776: in app
    await route.handle(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:297: in handle
    await self.app(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/starlette/routing.py:72: in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:278: in app
    raw_response = await run_endpoint_function(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/routing.py:191: in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/api/v1/endpoints/auth.py:22: in register_user
    result = await db.execute(select(User).where(User.email == user_in.email))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py:463: in execute
    result = await greenlet_spawn(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2365: in execute
    return self._execute_internal(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:2251: in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/context.py:306: in orm_execute_statement
    result = conn.execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1415: in execute
    return meth(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:523: in _execute_on_connection
    return connection._execute_clauseelement(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1637: in _execute_clauseelement
    ret = self._execute_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1842: in _execute_context
    return self._exec_single_context(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1982: in _exec_single_context
    self._handle_dbapi_exception(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2351: in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1963: in _exec_single_context
    self.dialect.do_execute(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py:943: in do_execute
    cursor.execute(statement, parameters)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:580: in execute
    self._adapt_connection.await_(
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:515: in _prepare_and_execute
    await adapt_connection._start_transaction()
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:845: in _start_transaction
    self._handle_exception(error)
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:792: in _handle_exception
    raise translated_error from error
E   sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
E   [SQL: SELECT users.id, users.email, users.hashed_password 
E   FROM users 
E   WHERE users.email = $1::VARCHAR]
E   [parameters: ('test_login@example.com',)]
E   (Background on this error at: https://sqlalche.me/e/20/rvf5)
=============================== warnings summary ===============================
app/models/__init__.py:3
  /Users/salehgazwani/Documents/morvo13/app/models/__init__.py:3: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:323
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:323
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:323
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:323: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/passlib/utils/__init__.py:854
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/passlib/utils/__init__.py:854: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
    from crypt import crypt as _crypt

../../../../opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py:259
  /opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py:259: DeprecationWarning: FUNCTIONS is deprecated and will be removed in future versions
    enum_member = enum_class._new_member_(enum_class, *args)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/instructor/dsl/citation.py:1
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/instructor/dsl/citation.py:1
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/instructor/dsl/citation.py:1: DeprecationWarning: Importing FieldValidationInfo from `pydantic` is deprecated. This feature is either no longer supported, or is not public.
    from pydantic import BaseModel, Field, FieldValidationInfo, model_validator

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic_core/core_schema.py:4324
../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic_core/core_schema.py:4324
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic_core/core_schema.py:4324: DeprecationWarning: `FieldValidationInfo` is deprecated, use `ValidationInfo` instead.
    warnings.warn(msg, DeprecationWarning, stacklevel=1)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/crewai/telemetry/telemetry.py:7
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/crewai/telemetry/telemetry.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
    import pkg_resources

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3146
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3146
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:2558
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:2558: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(parent)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:918
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:918: UserWarning: Mixing V1 models and V2 models (or constructs, like `TypeAdapter`) is not supported. Please upgrade `CrewAgentExecutor` to V2.
    warn(

app/main.py:19
  /Users/salehgazwani/Documents/morvo13/app/main.py:19: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    @app.on_event("startup")

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:4495
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/fastapi/applications.py:4495: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    return self.router.on_event(event_type)

../../Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py:1474
  /Users/salehgazwani/Library/Caches/pypoetry/virtualenvs/morvo12-I06tqVVy-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py:1474: PytestConfigWarning: Unknown config option: async_collection_loop
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/api/v1/endpoints/test_auth.py::test_register_user - RuntimeError...
FAILED tests/api/v1/endpoints/test_auth.py::test_login_access_token - sqlalch...
ERROR tests/api/v1/endpoints/test_seranking.py::test_analyze_domain_queues_task
ERROR tests/api/v1/endpoints/test_seranking.py::test_get_domain_history - sql...
ERROR tests/api/v1/endpoints/test_seranking.py::test_get_domain_history - sql...
============== 2 failed, 1 passed, 18 warnings, 3 errors in 3.40s ==============
